version: '3'

services:
  llm-service:
    build:
      context: ./main_service
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - postgres

  main-service:
    build:
      context: ./main_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
      - llm-service
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-1:5432/hrter 
      LLM_SERVICE_URL: http://hrter-llm-service-1:8001

  postgres:
    image: postgres:14
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrter
    ports:
      - "5434:5432"
    volumes:
      - ./main_service/migrations:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
