version: '3'

services:
  python-service:
    hostname: python-service
    build:
      context: ./llm_service
    ports:
      - "8001:8001"
    networks:
      - app-network
  main-service:
    hostname: main-service
    build:
      context: ./llm_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - python-service
    environment:
      - PYTHON_SERVICE_HOST=python-service
      - PYTHON_SERVICE_PORT=8001
networks:
  app-network:
    driver: bridge