version: '3'

services:
  llm-service:
    build:
      context: ./llm_service
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FOLDER_PATH=cv

  main-service:
    build:
      context: ./main_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
      - llm-service
    environment:
      - DATABASE_URL=${DB_URL}
      - LLM_SERVICE_URL=${LLM_SERVICE_URL}

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hrter
    ports:
      - "5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./main_service/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
